trigger:
- master

pool:
  name: 'Default'  
  demands:
    - agent.name -equals agentTest 

steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'MSBuild'
    projectKey: 'test'
    projectName: 'test'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '2eed1aca-5e9e-41cc-9947-25e256bbcd2c/ca03e69e-8777-409e-a7fa-8619a201930b'
  displayName: 'Restore .NET Project with NuGet'

- script: java -version
  displayName: 'Check Java Version'

- script: |
    # Format the version number (e.g., 1.0.$(Build.BuildId))
    versionNumber="1.0.$(Build.BuildId)"
    
    # Set the version as a pipeline variable
    echo "##vso[task.setvariable variable=packageVersion]$versionNumber"
    
    # Print the version to the console
    echo "Version number is: $versionNumber"
  displayName: 'Set Version Number'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'  # Adjust this if needed to point to your project files
    includeSymbols: true  # Include symbols if needed
    versioningScheme: 'byBuildNumber'  # Optional: Specify versioning scheme
    version: '$(packageVersion)'  # Use formatted version
  displayName: 'Pack .NET Project with NuGet'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- script: |
    # Get the current build ID (acting as version number)
    currentVersion=$(Build.BuildId)
    
    # Increment the build ID
    newVersion=$((currentVersion + 1))
    
    # Print the new version to the console
    echo "##vso[task.setvariable variable=version]$newVersion"
    echo "New version is: $newVersion"
    
  displayName: 'Increment and Print Version'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'  # Adjust this if needed to match your output package
    nuGetFeedType: 'internal'
    vstsFeed: '2eed1aca-5e9e-41cc-9947-25e256bbcd2c/ca03e69e-8777-409e-a7fa-8619a201930b'
  displayName: 'Push NuGet Package to Azure Artifacts'
