trigger:
- master

pool:
  name: 'Default'  
  demands:
    - agent.name -equals agentTest 

variables:
  sonarHostUrl: 'http://20.82.137.57:9000'
  sonarLogin: 'squ_c94a1619affde632fbccb10e9d6c8453d6f09527'
  sonarProjectKey: 'test'
  sonarProjectName: 'test'
  sonarProjectVersion: '1.0'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.400'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonarqube'
    scannerMode: 'MSBuild'
    projectKey: '$(sonarProjectKey)'
    projectName: '$(sonarProjectName)'
    projectVersion: '$(sonarProjectVersion)'
    extraProperties: |
      sonar.login=$(sonarLogin)
      sonar.host.url=$(sonarHostUrl)
  displayName: 'Prepare Analysis on SonarQube'

- script: |
    dotnet restore
    dotnet build --configuration Release
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Restore, Build and Pack .NET Project'

- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube Analysis'

- script: |
    # Get the current build ID (acting as version number)
    currentVersion=$(Build.BuildId)
    
    # Increment the build ID
    newVersion=$((currentVersion + 1))
    
    # Print the new version to the console
    echo "##vso[task.setvariable variable=version]$newVersion"
    echo "New version is: $newVersion"
    
  displayName: 'Increment and Print Version'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
  displayName: 'Publish Artifact to Pipeline'

- task: UniversalPackages@0
  displayName: Publish a Universal Package
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'hello_world/test'
    vstsFeedPackagePublish: 'helloworld'
    packagePublishDescription: 'hello world app'
