trigger:
- master

pool:
  name: 'Default'  
  demands:
    - agent.name -equals agentTest 

steps:
- checkout: self 

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.400'

- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'MSBuild'
    projectKey: 'test'
    projectName: 'test'

- script: java -version
  displayName: 'Check Java Version'

- script: |
    echo "Listing files in the root directory:"
    ls -la
  displayName: 'List Project Files'

- script: |
    dotnet restore --configfile nuget.config HelloWorldApp.csproj
  displayName: 'Restore NuGet Packages'

- script: |
    dotnet build --configuration Release HelloWorldApp.csproj
  displayName: 'Build Solution in Release Mode'

- task: SonarQubeAnalyze@6
  displayName: 'Run SonarQube Analysis'

- script: |
    currentVersion=$(Build.BuildId)
    echo "New version is: $currentVersion"
  displayName: 'Print Version'

- script: |
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory) HelloWorldApp.csproj
  displayName: 'Pack NuGet Package'

- task: UniversalPackages@0
  displayName: 'Publish a Universal Package'
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'hello_world/test'
    vstsFeedPackagePublish: 'hello_world'
