trigger:
- master

pool:
  name: 'Default'  
  demands:
    - agent.name -equals agentTest 

steps:
- checkout: self 

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.400'

- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'MSBuild'
    projectKey: 'test'
    projectName: 'test'

- script: java -version
  displayName: 'Check Java Version'

- script: |
    echo "Listing files in the root directory:"
    ls -la
    echo "Listing files in HelloWorld directory:"
    ls -la HelloWorld
  displayName: 'List Project Files'

- script: |
    dotnet restore --configfile nuget.config HelloWorld/HelloWorld.csproj
  displayName: 'Restore NuGet Packages'

- script: |
    dotnet build --configuration Release HelloWorld/HelloWorld.csproj
  displayName: 'Build Solution in Release Mode'

- task: SonarQubeAnalyze@6
  displayName: 'Run SonarQube Analysis'

- script: |
    currentVersion=$(Build.BuildId)
    echo "New version is: $currentVersion"
  displayName: 'Print Version'

- script: |
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory) HelloWorld/HelloWorld.csproj
  displayName: 'Pack NuGet Package'

- script: |
    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source "https://pkgs.dev.azure.com/lalush345/_packaging/lalush345/nuget/v3/index.json" --api-key "$(NuGetApiKey)"
  displayName: 'Push Package to Azure Artifacts'
