trigger:
- master

pool:
  name: 'Default'  # Your self-hosted agent pool

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x.x'  # Specify the .NET SDK version

- script: |
    dotnet restore
    dotnet build --configuration Release
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Restore, Build and Pack .NET Project'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
  displayName: 'Publish Artifact to Pipeline'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '<your-feed-name>'  # Replace with your Azure Artifacts feed name
    allowPackageConflicts: true
  displayName: 'Push Package to Azure Artifacts'

